[theme]
base = "dark"
primaryColor = "#65D9E8"
backgroundColor = "#07141D"
secondaryBackgroundColor = "#102A38"
textColor = "#E8F1F4"
font = "sans-serif"

[browser]
gatherUsageStats = false

[server]
headless = true
